--HAVING DÙNG SAU GROUP BY GIỐNG NHƯ WHERE ĐỂ XỬ LÝ NHỮNG MỤC ĐÃ GROUP BY
--CHO BIẾT NHŨNG KHÁCH HÀNG ĐÃ ĐẶT HƠN 20 ĐƠN, SẤP SẾP THEO TỔNG ĐƠN HÀNG GIẢM DẦN
SELECT [CustomerID], COUNT([OrderID]) AS SO_DON
FROM Orders
GROUP BY [CustomerID]
HAVING COUNT([OrderID])>20

--LỌC RA NHŨNG NHÀ CUNG CẤP CÓ SỐ HÀNG TRONG KHO UNITSINSTOCK > 30 VÀ TRUNG BÌNH GIÁ UNITPRICE < 50
SELECT [SupplierID], SUM([UnitsInStock]) AS TONG_KHO, AVG([UnitPrice]) AS TRUNG_BINH
FROM Products
GROUP BY [SupplierID]
HAVING SUM([UnitsInStock]) >30 AND AVG([UnitPrice]) < 50

--TỎNG TIỀN VẬN CHUYỂN TỪNG THÁNG, TRONG NỮA CUỐI NĂM 1996 THEO THỨ TỰ GIẢM DẦN
SELECT MONTH([ShippedDate]) AS THANG, SUM([Freight]) AS TONG_TIEN
FROM [dbo].[Orders]
WHERE [ShippedDate] BETWEEN '1996-7-1' AND '1996-12-31' 
GROUP BY MONTH([ShippedDate])
ORDER BY MONTH([ShippedDate]) ASC

--TỎNG TIỀN VẬN CHUYỂN > 1000 THEO TỪNG THÁNG, TRONG NỮA CUỐI NĂM 1996 THEO THỨ TỰ GIẢM DẦN
SELECT MONTH([ShippedDate]) AS THANG, SUM([Freight]) AS TONG_TIEN
FROM [dbo].[Orders]
WHERE [ShippedDate] BETWEEN '1996-7-1' AND '1996-12-31' 
GROUP BY MONTH([ShippedDate])
HAVING SUM([Freight]) > 1000
ORDER BY MONTH([ShippedDate]) ASC

--NHŨNG THÀNH PHỐ CÓ TỔNG DƠN LỚN HƠN 16, XẤP SẾP GIẢM DẦN
SELECT [ShipCity], COUNT([OrderID]) AS TONG
FROM [dbo].[Orders]
GROUP BY ShipCity
HAVING SUM([OrderID]) > 16
ORDER BY SUM([OrderID]) DESC