CREATE TABLE NHANVIEN(
	MaNV INT NOT NULL PRIMARY KEY,
	HoTeN VARCHAR(50) NOT NULL,
	Phai VARCHAR(50),
	NgaySinh DATE,
	DiaChi VARCHAR(255),
	SDT VARCHAR(10)
);

--SQL REGEX
CREATE TABLE KHACHHANG(
	MaKH INT IDENTITY(100,5) NOT NULL PRIMARY KEY,
	TenKH VARCHAR(50) NOT NULL,
	DiaChi VARCHAR(255),
	SDT VARCHAR(10) CHECK (SDT LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')
);

ALTER TABLE NHANVIEN
ADD Email VARCHAR(100)

ALTER TABLE NHANVIEN
ALTER COLUMN HoTeN VARCHAR(100)

ALTER TABLE NHANVIEN
RENAME COLUMN HoTeN TO HoTen;

TRUNCATE TABLE NHANVIEN --XÓA DŨ LIỆU BẢNG
DROP TABLE NHANVIEN --XÓA LUÔN CÁI BẢNG


--BAI TAP
CREATE TABLE SINHVIEN(
	MaSV INT NOT NULL PRIMARY KEY,
	HoTen VARCHAR(100) NOT NULL,
	Lop VARCHAR(20),
	Nganh VARCHAR(20),
	Diemtb FLOAT
);

ALTER TABLE SINHVIEN
ADD Email VARCHAR(100)

ALTER TABLE SINHVIEN
ALTER COLUMN Diemtb DECIMAL(2,1)


